# エラーの処理

Parseには、エラーの表面化とコード内での処理に対してシンプルなパターンがいくつかあります。

発生するエラーは2種類あります。まずは、SDK使用中にロジックエラーに対応するものがあります。このタイプのエラーでは`NSException`が発生します。たとえば、次のコードを見てください。

```objc
PFUser *user = [PFUser user];
[user signUp];
```

ここでは、必須のプロパティ（`username`と`password`）を設定せずに`signUp`が呼び出されたために`NSInternalInconsistencyException`が返されています。

もう1つのエラーの種類は、ネットワーク上でParseクラウドとやり取りする際に発生するものです。こうしたエラーは、クラウドへの接続問題や要請された演算子の実行問題のいずれかに関連しています。別の例を見てみましょう。

```objc
- (void)getMyNote {
    PFQuery *query = [PFQuery queryWithClassName:@"Note"];
    [query getObjectInBackgroundWithId:@"thisObjectIdDoesntExist"
           target:self 
           selector:@selector(callbackForGet:error:)];
}
```

上記のコードでは、存在しない`objectId`でオブジェクトを取得しようとしています。Parseクラウドでは、`code`で設定したエラーコードとエラーの`userInfo`のメッセージでエラーを返します。コールバックで正しく対処する方法はこちらです。

```objc
- (void)callbackForGet:(PFObject *)result error:(NSError *)error {
    if (result) {
        NSLog(@"Everything went fine!");
    } else {
        if ([error code] == kPFErrorObjectNotFound) {
            NSLog(@"Uh oh, we couldn't find the object!");
        } else if (error) {
            NSLog(@"Error: %@", [error userInfo][@"error"]);
        }
    }
}
```

また、デバイスがParseクラウドに接続できなかったためにクエリが失敗する場合があります。こちらは同じコールバックですが、このシナリオを明確に処理するコードが追加されています。

```objc
- (void)callbackForGet:(PFObject *)result error:(NSError *)error {
    if (result) {
        NSLog(@"Everything went fine!");
    } else {
        if ([error code] == kPFErrorObjectNotFound) {
            NSLog(@"Uh oh, we couldn't find the object!");
            // Now also check for connection errors:
        } else if ([error code] == kPFErrorConnectionFailed) {
            NSLog(@"Uh oh, we couldn't even connect to the Parse Cloud!");
        } else if (error) {
            NSLog(@"Error: %@", [error userInfo][@"error"]);
        }
    }
}
```

コールバックで`NSNumber`が予測される場合、`boolValue`では操作が正常にできたかどうかを表示します。たとえば、`%{ParseObject}`の`saveInBackgroundWithTarget:selector:`メソッドのコールバックを実装する方法はこちらです。

```objc
- (void)callbackForSave:(NSNumber *)result error:(NSError *)error {
    if ([result boolValue]) {
        NSLog(@"Everything went fine!");
    } else {
        if ([error code] == kPFErrorConnectionFailed) {
            NSLog(@"Uh oh, we couldn't even connect to the Parse Cloud!");
        } else if (error) {
            NSLog(@"Error: %@", [error userInfo][@"error"]);
        }
    }
}
```

同期（非バックグラウンド）メソッドでは、エラーかの処理はほとんど同様です。ただし、`NSNumber`が成功か失敗かを表示する代わりに、実際の`BOOL`を直接取得します。

デフォルトでは、すべての接続には10秒間のタイムアウトがあるので、同期メソッドは永久にハングされません。

出現する可能性のある`NSError`タイプの全リストについては、[API](/docs/ios)エラーコードセクションを確認してください。
