# 处理错误

Parse 有几种简单的模式可以发现您代码中错误并在进行处理。

您可能会遇到两类错误。第一类是关于您在使用 SDK 时的逻辑错误。这类错误会造成 `NSException` 增多。相关示例请参阅以下代码：

```objc
PFUser *user = [PFUser user];
[user signUp];
```

这将引发 `NSInternalInconsistencyException`，因为要求的属性（`username` 和 `password`）尚未设置就调用了 `signUp`。

第二类是通过网络与 Parse 云交互时出现的错误。这些错误要么关乎与云有关的问题，要么关乎与执行所请求操作相关的问题。我们再来看一个示例：

```objc
- (void)getMyNote {
    PFQuery *query = [PFQuery queryWithClassName:@"Note"];
    [query getObjectInBackgroundWithId:@"thisObjectIdDoesntExist"
           target:self 
           selector:@selector(callbackForGet:error:)];
}
```

在上面的代码中，我们尝试用不存在的 `objectId` 提取一个对象。Parse 云将返回一个错误，错误代码设置在 `code` 中，错误消息设置在该错误的 `userInfo` 中。可以使用以下代码在您的回调中正确处理错误：

```objc
- (void)callbackForGet:(PFObject *)result error:(NSError *)error {
    if (result) {
        NSLog(@"Everything went fine!");
    } else {
        if ([error code] == kPFErrorObjectNotFound) {
            NSLog(@"Uh oh, we couldn't find the object!");
        } else if (error) {
            NSLog(@"Error: %@", [error userInfo][@"error"]);
        }
    }
}
```

设备无法连接到 Parse 云也可能造成查询失败。以下是用于处理上述情况的同一组回调代码，但其中包含了一些额外代码：

```objc
- (void)callbackForGet:(PFObject *)result error:(NSError *)error {
    if (result) {
        NSLog(@"Everything went fine!");
    } else {
        if ([error code] == kPFErrorObjectNotFound) {
            NSLog(@"Uh oh, we couldn't find the object!");
            // Now also check for connection errors:
        } else if ([error code] == kPFErrorConnectionFailed) {
            NSLog(@"Uh oh, we couldn't even connect to the Parse Cloud!");
        } else if (error) {
            NSLog(@"Error: %@", [error userInfo][@"error"]);
        }
    }
}
```

如果回调在等待 `NSNumber`，其 `boolValue` 将告诉您操作成功与否。例如，您可以通过这种方式回调 `%{ParseObject}` 的 `saveInBackgroundWithTarget:selector:` 方法：

```objc
- (void)callbackForSave:(NSNumber *)result error:(NSError *)error {
    if ([result boolValue]) {
        NSLog(@"Everything went fine!");
    } else {
        if ([error code] == kPFErrorConnectionFailed) {
            NSLog(@"Uh oh, we couldn't even connect to the Parse Cloud!");
        } else if (error) {
            NSLog(@"Error: %@", [error userInfo][@"error"]);
        }
    }
}
```

对于同步（非后台）方法，错误处理大致相同，不同的地方在于并没有表示是否成功的 `NSNumber`，而是直接提供一个真实的 `BOOL`。

默认情况下，所有连接的超时时间是 10 秒，所以同步方法不会不确定地挂起。

如需了解所有可能的 `NSError` 类型，请查看 [API](/docs/ios) [API](/docs/osx) 的&ldquo;错误代码&rdquo;部分。
